### PR TITLE
Fixes and improvements

### PR DESCRIPTION
**Pull request by ghost**
I am an avid fan of Bitgesell as a store-of-value deflationary cryptocurrency, and have been following it for several years. I've invested parts of my savings into the currency, and plan on making considerable additional investments in the future. As an investor, I have a vested interest in the continuing success of the project, and wish to do whatever I can to give my part.

It has come to my attention that you have recently ported the BGL/EVM bridge backend to Go. As it so happens, I am a senior Go engineer by trade myself, and saw an opportunity to contribute! By reading through the code, I noticed several issues that could be fixed, as well as some general improvements to be made. This PR is an aggregation of some of such fixes and improvements.

### Changes

1. Use the `github.com/bitgesellofficial/go-bgld` library instead of `github.com/toorop/go-bitcoind` in order to support returning the last block hash in the `ListSinceBlock` RPC method (see https://github.com/BitgesellOfficial/go-bgld/pull/1).
2. Files containing secrets should never be committed to version control. `config.yml` is currently part of the repository, making it possible to accidentally commit secrets. A common pattern to prevent this is to have an example config/env file included in the repo, and the actual config/env file explicitly excluded via `.gitignore`. I've implemented that pattern here by renaming `config.yml` to `config-example.yml`, and adding `config.yml` to `.gitignore`.
3. WBGL->BGL bridge has a small bug where, with certain precision of WBGL sent to the bridge, the resulting BGL amount after deducting the fee would end up with more than 8 decimal places (which is the maximum allowed precision in the Bitcoin protocol). This would cause the RPC node to return an error, causing the bridge to return the WBGL to the sender. I've fixed the bug by applying floating point truncation to the amount.
4. HTTP service static content serving function is using string concatenation (`filesDir+r.URL.Path`) to devise file path. This is potentially insecure. I've refactored the function to construct the path more securely, as well as making a few additional minor improvements to the code.
5. Slightly refactored the redis package to make the code easier to read and logic easier to follow.
6. Refactored the way EVM blockchains are being interacted with by the application. Specifically, the way fallback RPCs are being used. Currently, these are only used if the connection cannot be established initially. However, sometimes these RPC APIs block requests due to rate limiting (too many requests made in a certain time period). Current implementation has no way to fall back to other RPC APIs in such a case, causing an issue where creating a transaction or even getting WBGL balance for a blockchain sometimes fails. Specifically, it Arbitrum seems to be affected most often. This PR should fix these problems. I've made the following changes to fix the issue:
    - Removed the current `GetClient` approach and replaced it with a `WithClient` wrapper to be able to use the fallback mechanism for any RPC request.
    - Updated the code where RPC requests are being made.
    - Refactored the `scanEVM` worker to use the same mechanism, as opposed to the separate `jsonrpc` approach, in order to ensure that fallback RPCs are being utilized across the board.

### Conclusion

This is not an exhaustive list of improvements that could be made to increase the overall quality of the bridge backend codebase. I have additional ideas, including some higher level abstract ideas to make the code more idiomatic, but decided against including them in this initial PR so as not to bloat it up with changes. If it is amenable to the maintainers of the project, I would happily involve myself more. Feel free to let me know in the comments.

I will happily contribute free of charge, but if you wish to reimburse my efforts, I will not object! I would invest it back into Bitgesell if that were the case. ETH/BNB/ARB/OP address: `0xDef01E22C052e24C9aABd34960dd917d4715ADA9`, BGL: `bgl1q8j8jm976qgyuflm8kzz50zsruzhsvk7yvzuqtz`. @wu-emma

Looking forward to contributing more in the future!

Regards,
Devon

### CODE REVIEW

**Comment by ghost** [comment]
@van-orton @wu-emma

**Comment by ghost** [comment]
It has come to my attention that the users of the bridge have been having problems swapping between mainnet BGL and Arbitrum WBGL. After doing some testing in my local development environment, I observed in the logs that the RPC endpoints would occasionally fail executing queries due to too many requests being made. This seemed to affect Arbitrum more than any other EVM blockchain for some reason, even though most of them are configured to use ankr as the main RPC endpoint.

Looking into the current implementation, I found that the fallback RPC endpoints are only being utilized when the initial connection to the primary one fails. This does not take into account the case where requests fail due to rate limiting. Furthermore, the EVM transaction scanner worker (`Worker_scanEVM`) doesn't use any fallback RPCs at all.

To fix these issues, I've refactored the way EVM RPC endpoints are being interacted with to use the fallback URLs when any request fails. See count 6 in the edited original comment for this PR for a detailed explanation.

Note: after deploying these changes, delete the `BGLBlockHash` key in Redis to have the service rescan the incoming BGL transactions and execute any bridge operations that have failed due to EVM RPC issues. The service ignores the transactions that have already been successfully bridged so there is no danger of double spend.

@van-orton @wu-emma Please review this PR as soon as possible in order to address problems that the users have been having with the service.

**Comment by van-orton** [comment]
Yes, the changes look good.
Beyond the cosmetics, however, the main issue is RPC instability (free RPC) for EVM networks. When the scanning of blocks fails, it does not update the last block scanned, so it would catch up eventually. Refactoring of retries also is practically the same logic except the code, there are other updates that need to be done probably in that direction.
There are following errors that occur:
- i don't know why, but sometimes bridge requests come very close together, especially when doing from BGL->WBGL, and get in the same block. Therefore processing BGL->WBGL transfers one-by-one fails incorrectly due to holder EOA nonce not updating properly (and incorrectly reported by RPC), making local handling of nonce is in some areas worse because would make service stall if out of sync. Probably a new mechanism is required to have delays between making EVM transactions like a queue for a chain;
- gas errors (rarely) of base fee < gas value (probably was fixed);
- sometimes the EVM tx hash is received, but the tx itself is missing (this is the weirdest case of them all);

Still, a good chunk of improvements, merging this and notify @wu-emma about the greenlight. Great job!
Would update running bridge to the latest code updates as well.

**Comment by wu-emma** [comment]
Hi @0xdevolution !
0xc1a1eeaa1774731f6a946efa8d022e52ba9e66c61d0b0997263f55e3340963ce (Eth)
Thank you for the contribution! I think stabilizing the bridge is pretty important at the moment.

**Comment by ghost** [comment]
> Refactoring of retries also is practically the same logic except the code, there are other updates that need to be done probably in that direction.

It's actually not the same logic, because the previous code only reached for the fallback URLs when the **initial connection** failed, which would only happen if the first RPC on the list is unreachable. All the following requests would be made via the same client instance that was being kept open for the duration of the application running. The refactored version will use the fallback URLs on case-by-case basis whenever a single request is unsuccessful.

I do agree though that the scanning of blocks would eventually be successful in case the rate-limiting issue is encountered. That's probably why there seem not to be any issue reports from bridge users regarding the EVM -> BGL direction.

Regarding the nonce issues, you are right that probably a different approach would be warranted. Perhaps implementing a queue for outgoing transactions that is executed in a separate worker thread would solve these issues.

@wu-emma thank you! I will happily help in whatever way I can. I will look into the aforementioned implementation of transaction queue worker next, unless there are any objections.

**Comment by ghost** [comment]
@van-orton Did you end up deploying the updated code to the bridge? I saw some reports that people are still having issues and was wondering if it had anything to do with the update.

I've also created a new PR addressing the nonce issues in case you haven't seen it yet (#2). Let me know if you have any questions or if I can assist in any way. If there are still issues, feel free to share the details in the discussion section, or contact me directly via Discord (my username is 0xdevolution) or e-mail (0xdevolution@gmail.com).

**Comment by leetdev** [comment]
@van-orton @wu-emma Any updates on this? People are still reporting issues. I performed a small bridge test as well on Arbitrum (BGL to EVM direction) a few days ago, and it never got through. You said fixing the bridge was a priority, yet it's been a week without any info or updates.

**Pull request merged**
