### PR TITLE
Improve handling of EVM nonces

### PR DESCRIPTION
**Pull request by ghost**
Following the discussion in #1, I looked into how to improve how the bridge handles outgoing EVM transactions. Initially, I figured a transaction queue handled by a separate worker might be in order, but on second thought, I think that it's actually not necessary. Currently, whenever a new transaction is created, the current pending nonce is being requested from the blockchain. This, however, fails to take into account that when two transactions happen to land in the same block, the pending nonce will not be updated by the time the second transaction is being created. This can be fixed easily by keeping track of the nonce locally. I've implemented the fix here by only querying the RPC for the pending nonce for each chain upon initialization, and then incrementing the values locally whenever a new transaction is successfully created.

After implementing this quick fix, I realized that this simple approach will fail in case there are any outgoing transactions created externally. I've addressed this by going back to checking the pending nonce on the blockchain when creating a new transaction, but only updating the local value in case it's higher than the current one.

Additionally, I've updated the dependencies to the latest versions. This includes the `go-bgld` library since the update PR has been merged in the official repository (removing the need to use the replacement version from my forked repository).

### CODE REVIEW

**Comment by van-orton** [comment]
Hey @0xdevolution !
Yes, deployed to bridge yesterday the code updates merged from PR #1
thanks for updates, yes, this would help, give me a 1-2 days preparing a similar approach with added queue checking transaction receipts. We combine them and merge to be more fault-tolerant.

**Comment by ghost** [comment]
Hi @van-orton, are you sure you successfully deployed it? The bridge seems to be still reporting sporadic server errors when querying account balances, perhaps the fallback RPC client queue isn't working properly? I am unable to replicate this issue when running the updated code locally, which is why I'm wondering if the updates were deployed properly.

**Comment by ghost** [comment]
Hello @van-orton, any updates on this? BGL->Arbitrum operations still don't seem to be going through (I tested personally with 9.8 BGL last week and 0.1 BGL yesterday, neither transaction was bridged nor returned). Looking at the `returnfail` logs, it seems like an API is throwing errors regarding transfer method not being allowed (which I'm guessing is a limitation on some of the free RPC services). In addition, I discovered an entry in the log from yesterday with a `-3: Invalid amount` error message from the Bitgesell RPC, which indicates that my fix that truncates the excess decimal places from the amount before calling the RPC isn't working for some reason. I've tested this locally and it shouldn't happen with the latest version of the bridge, which seems to indicate that the changes have not been actually deployed. That might also explain why the Arbitrum transfers aren't going through as the new code should automatically try a different RPC API when that happens, but it could also be a separate issue.

**Comment by naftalimurgor** [comment]
Hey @0xdevolution 
What does this commit introduce to go-bgld library? Seems the official `go-bgld` is being replaced with your own fork in this commit?

https://github.com/BitgesellOfficial/go-bgld/compare/master...0xdevolution:go-bgld:master#diff-71cbcc587d27d338525d1b533cec40432e5cdd66c2450e669f69622d9a2f58edR748

**Pull request closed without merging**
